package com.example.mmowgli_explore;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ShortcutAction;
import com.vaadin.event.ShortcutListener;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class CardCreator extends CustomComponent{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TextArea textArea_tag;
	@AutoGenerated
	private Label label_tag;
	@AutoGenerated
	private TabSheet tabSheet;
	@AutoGenerated
	private VerticalLayout verticalLayout_Adapt;
	@AutoGenerated
	private TextArea textArea_Adapt;
	@AutoGenerated
	private VerticalLayout verticalLayout_Counter;
	@AutoGenerated
	private TextArea textArea_Counter;
	@AutoGenerated
	private VerticalLayout verticalLayout_Explore;
	@AutoGenerated
	private TextArea textArea_Explore;
	@AutoGenerated
	private VerticalLayout verticalLayout_Expand;
	@AutoGenerated
	private TextArea textArea_Expand;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CardCreator() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		textArea_Expand.addShortcutListener(new ShortcutListener("Shortcut Name", ShortcutAction.KeyCode.ENTER, null) {
			@Override
			public void handleAction(Object sender, Object target) {
				// your code here
				
			}
		});
		
		tabSheet.getTab(verticalLayout_Expand).setStyleName("Expand");
		tabSheet.getTab(verticalLayout_Explore).setStyleName("Explore");
		tabSheet.getTab(verticalLayout_Counter).setStyleName("Counter");
		tabSheet.getTab(verticalLayout_Adapt).setStyleName("Adapt");
		
	}
	
	public TextArea getTextArea_Adapt() {
		return textArea_Adapt;
	}

	public void setTextArea_Adapt(TextArea textArea_Adapt) {
		this.textArea_Adapt = textArea_Adapt;
	}

	public TextArea getTextArea_Counter() {
		return textArea_Counter;
	}

	public void setTextArea_Counter(TextArea textArea_Counter) {
		this.textArea_Counter = textArea_Counter;
	}

	public TextArea getTextArea_Explore() {
		return textArea_Explore;
	}

	public void setTextArea_Explore(TextArea textArea_Explore) {
		this.textArea_Explore = textArea_Explore;
	}

	public TextArea getTextArea_Expand() {
		return textArea_Expand;
	}

	public void setTextArea_Expand(TextArea textArea_Expand) {
		this.textArea_Expand = textArea_Expand;
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("355px");
		mainLayout.setHeight("260px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("355px");
		setHeight("260px");
		
		// tabSheet
		tabSheet = buildTabSheet();
		mainLayout.addComponent(tabSheet);
		mainLayout.setExpandRatio(tabSheet, 1.0f);
		
		// label_tag
		label_tag = new Label();
		label_tag.setStyleName("title");
		label_tag.setImmediate(false);
		label_tag.setWidth("-1px");
		label_tag.setHeight("-1px");
		label_tag.setValue("Tags:");
		mainLayout.addComponent(label_tag);
		mainLayout.setExpandRatio(label_tag, 0.15f);
		mainLayout.setComponentAlignment(label_tag, new Alignment(33));
		
		// textArea_tag
		textArea_tag = new TextArea();
		textArea_tag.setImmediate(false);
		textArea_tag.setWidth("100.0%");
		textArea_tag.setHeight("100.0%");
		textArea_tag.setInputPrompt("Insert Tags Here...");
		textArea_tag.setMaxLength(100);
		mainLayout.addComponent(textArea_tag);
		mainLayout.setExpandRatio(textArea_tag, 0.3f);
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet() {
		// common part: create layout
		tabSheet = new TabSheet();
		tabSheet.setImmediate(true);
		tabSheet.setWidth("100.0%");
		tabSheet.setHeight("100.0%");
		
		// verticalLayout_Expand
		verticalLayout_Expand = buildVerticalLayout_Expand();
		tabSheet.addTab(verticalLayout_Expand, "Expand", null);
		
		// verticalLayout_Explore
		verticalLayout_Explore = buildVerticalLayout_Explore();
		tabSheet.addTab(verticalLayout_Explore, "Explore", null);
		
		// verticalLayout_Counter
		verticalLayout_Counter = buildVerticalLayout_Counter();
		tabSheet.addTab(verticalLayout_Counter, "Counter", null);
		
		// verticalLayout_Adapt
		verticalLayout_Adapt = buildVerticalLayout_Adapt();
		tabSheet.addTab(verticalLayout_Adapt, "Adapt", null);
		
		return tabSheet;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Expand() {
		// common part: create layout
		verticalLayout_Expand = new VerticalLayout();
		verticalLayout_Expand.setImmediate(false);
		verticalLayout_Expand.setWidth("100.0%");
		verticalLayout_Expand.setHeight("100.0%");
		verticalLayout_Expand.setMargin(false);
		
		// textArea_Expand
		textArea_Expand = new TextArea();
		textArea_Expand.setImmediate(false);
		textArea_Expand.setWidth("100.0%");
		textArea_Expand.setHeight("100.0%");
		textArea_Expand.setInputPrompt("Share your thoughts");
		textArea_Expand.setMaxLength(150);
		verticalLayout_Expand.addComponent(textArea_Expand);
		
		return verticalLayout_Expand;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Explore() {
		// common part: create layout
		verticalLayout_Explore = new VerticalLayout();
		verticalLayout_Explore.setImmediate(false);
		verticalLayout_Explore.setWidth("100.0%");
		verticalLayout_Explore.setHeight("100.0%");
		verticalLayout_Explore.setMargin(false);
		
		// textArea_Explore
		textArea_Explore = new TextArea();
		textArea_Explore.setImmediate(false);
		textArea_Explore.setWidth("100.0%");
		textArea_Explore.setHeight("100.0%");
		textArea_Explore.setInputPrompt("Share your thoughts");
		textArea_Explore.setMaxLength(150);
		verticalLayout_Explore.addComponent(textArea_Explore);
		
		return verticalLayout_Explore;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Counter() {
		// common part: create layout
		verticalLayout_Counter = new VerticalLayout();
		verticalLayout_Counter.setImmediate(false);
		verticalLayout_Counter.setWidth("100.0%");
		verticalLayout_Counter.setHeight("100.0%");
		verticalLayout_Counter.setMargin(false);
		
		// textArea_Counter
		textArea_Counter = new TextArea();
		textArea_Counter.setImmediate(false);
		textArea_Counter.setWidth("100.0%");
		textArea_Counter.setHeight("100.0%");
		textArea_Counter.setInputPrompt("Share your thoughts");
		textArea_Counter.setMaxLength(150);
		verticalLayout_Counter.addComponent(textArea_Counter);
		
		return verticalLayout_Counter;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Adapt() {
		// common part: create layout
		verticalLayout_Adapt = new VerticalLayout();
		verticalLayout_Adapt.setImmediate(false);
		verticalLayout_Adapt.setWidth("100.0%");
		verticalLayout_Adapt.setHeight("100.0%");
		verticalLayout_Adapt.setMargin(false);
		
		// textArea_Adapt
		textArea_Adapt = new TextArea();
		textArea_Adapt.setImmediate(false);
		textArea_Adapt.setWidth("100.0%");
		textArea_Adapt.setHeight("100.0%");
		textArea_Adapt.setInputPrompt("Share your thoughts");
		textArea_Adapt.setMaxLength(150);
		verticalLayout_Adapt.addComponent(textArea_Adapt);
		
		return verticalLayout_Adapt;
	}

}
