package com.example.mmowgli_explore;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ShortcutAction;
import com.vaadin.event.ShortcutListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class RootCardCreator extends CustomComponent{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private NativeButton nativeButton_submit;
	@AutoGenerated
	private TextArea textArea_tags;

	@AutoGenerated
	private Label label_tag;
	@AutoGenerated
	private TabSheet tabSheet;
	@AutoGenerated
	private VerticalLayout verticalLayout_Root2;
	@AutoGenerated
	private TextArea textArea_Root2;
	@AutoGenerated
	private VerticalLayout verticalLayout_Root1;
	@AutoGenerated
	private TextArea textArea_Root1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RootCardCreator() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		textArea_Root2.addShortcutListener(new ShortcutListener("Shortcut Name", ShortcutAction.KeyCode.ENTER, null) {
			@Override
			public void handleAction(Object sender, Object target) {
				// your code here
				
			}
			});
		
		tabSheet.getTab(verticalLayout_Root1).setStyleName("Root1");
		tabSheet.getTab(verticalLayout_Root2).setStyleName("Root2");
		
		nativeButton_submit.setCaption(null);
		nativeButton_submit.setIcon(new ThemeResource("images/icons/cards/plus.png"));
		nativeButton_submit.setStyleName("cardButtons");
		
	}
	


	public TabSheet getTabSheet() {
		return tabSheet;
	}



	public void setTabSheet(TabSheet tabSheet) {
		this.tabSheet = tabSheet;
	}



	public VerticalLayout getVerticalLayout_Root2() {
		return verticalLayout_Root2;
	}



	public void setVerticalLayout_Root2(VerticalLayout verticalLayout_Root2) {
		this.verticalLayout_Root2 = verticalLayout_Root2;
	}



	public VerticalLayout getVerticalLayout_Root1() {
		return verticalLayout_Root1;
	}



	public void setVerticalLayout_Root1(VerticalLayout verticalLayout_Root1) {
		this.verticalLayout_Root1 = verticalLayout_Root1;
	}



	public NativeButton getNativeButton_submit() {
		return nativeButton_submit;
	}



	public TextArea getTextArea_Root2() {
		return textArea_Root2;
	}



	public TextArea getTextArea_Root1() {
		return textArea_Root1;
	}

	public TextArea getTextArea_tags() {
		return textArea_tags;
	}




	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("263px");
		mainLayout.setHeight("260px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("263px");
		setHeight("260px");
		
		// tabSheet
		tabSheet = buildTabSheet();
		mainLayout.addComponent(tabSheet);
		mainLayout.setExpandRatio(tabSheet, 1.0f);
		
		// label_tag
		label_tag = new Label();
		label_tag.setStyleName("title");
		label_tag.setImmediate(false);
		label_tag.setWidth("-1px");
		label_tag.setHeight("-1px");
		label_tag.setValue("Tags:");
		mainLayout.addComponent(label_tag);
		mainLayout.setExpandRatio(label_tag, 0.15f);
		
		// textArea_tags
		textArea_tags = new TextArea();
		textArea_tags.setImmediate(false);
		textArea_tags.setWidth("100.0%");
		textArea_tags.setHeight("100.0%");
		textArea_tags.setInputPrompt("Insert Tags Here...");
		textArea_tags.setMaxLength(100);
		mainLayout.addComponent(textArea_tags);
		mainLayout.setExpandRatio(textArea_tags, 0.3f);
		
		// nativeButton_submit
		nativeButton_submit = new NativeButton();
		nativeButton_submit.setCaption("Submit");
		nativeButton_submit.setImmediate(true);
		nativeButton_submit.setWidth("-1px");
		nativeButton_submit.setHeight("-1px");
		mainLayout.addComponent(nativeButton_submit);
		mainLayout.setExpandRatio(nativeButton_submit, 0.1f);
		mainLayout
				.setComponentAlignment(nativeButton_submit, new Alignment(10));
		
		return mainLayout;
	}



	@AutoGenerated
	private TabSheet buildTabSheet() {
		// common part: create layout
		tabSheet = new TabSheet();
		tabSheet.setImmediate(true);
		tabSheet.setWidth("100.0%");
		tabSheet.setHeight("100.0%");
		
		// verticalLayout_Root1
		verticalLayout_Root1 = buildVerticalLayout_Root1();
		tabSheet.addTab(verticalLayout_Root1, "Root1", null);
		
		// verticalLayout_Root2
		verticalLayout_Root2 = buildVerticalLayout_Root2();
		tabSheet.addTab(verticalLayout_Root2, "Root2", null);
		
		return tabSheet;
	}



	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Root1() {
		// common part: create layout
		verticalLayout_Root1 = new VerticalLayout();
		verticalLayout_Root1.setCaption("Root1");
		verticalLayout_Root1.setImmediate(false);
		verticalLayout_Root1.setWidth("100.0%");
		verticalLayout_Root1.setHeight("100.0%");
		verticalLayout_Root1.setMargin(false);
		
		// textArea_Root1
		textArea_Root1 = new TextArea();
		textArea_Root1.setImmediate(false);
		textArea_Root1.setWidth("100.0%");
		textArea_Root1.setHeight("100.0%");
		textArea_Root1.setInputPrompt("Share your thoughts");
		textArea_Root1.setMaxLength(150);
		verticalLayout_Root1.addComponent(textArea_Root1);
		
		return verticalLayout_Root1;
	}



	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Root2() {
		// common part: create layout
		verticalLayout_Root2 = new VerticalLayout();
		verticalLayout_Root2.setCaption("Root2");
		verticalLayout_Root2.setImmediate(false);
		verticalLayout_Root2.setWidth("100.0%");
		verticalLayout_Root2.setHeight("100.0%");
		verticalLayout_Root2.setMargin(false);
		
		// textArea_Root2
		textArea_Root2 = new TextArea();
		textArea_Root2.setImmediate(false);
		textArea_Root2.setWidth("100.0%");
		textArea_Root2.setHeight("100.0%");
		textArea_Root2.setInputPrompt("Share your thoughts");
		textArea_Root2.setMaxLength(150);
		verticalLayout_Root2.addComponent(textArea_Root2);
		
		return verticalLayout_Root2;
	}

}
