package com.example.mmowgli_updates;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;

public class HomePageUpdates extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private GridLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;

	@AutoGenerated
	private PopularCards popularCards_2;

	@AutoGenerated
	private PopularTags popularTags_2;

	@AutoGenerated
	private PopularCards popularCards_1;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;

	@AutoGenerated
	private Label label_3;

	@AutoGenerated
	private Label label_2;

	@AutoGenerated
	private Label label_1;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;

	@AutoGenerated
	private RecentlyPlayed recentlyPlayed_1;

	@AutoGenerated
	private TrendingTags trendingTags_2;

	@AutoGenerated
	private TrendingCards trendingCards_1;

	private PopularTags popularTagList;
	private TrendingTags trendingTagList;
	
	private boolean showRootCards = true;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HomePageUpdates() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here

		
		trendingCards_1.setStyleName("updateBorders");
		trendingTags_2.setStyleName("updateBorders");
		popularCards_1.setStyleName("updateBorders");
		popularTags_2.setStyleName("updateBorders");
		label_1.setStyleName("updateBorders");
		label_2.setStyleName("updateBorders");
		
		
		//root card stuff
		//initToggle();
		
		
		//labels
		label_1.setValue(null);
		label_2.setValue(null);
		label_3.setValue(null);
		//label_4.setValue(null);
		//label_5.setValue(null);
		//label_6.setValue(null);
		//label_7.setValue(null);
		
		label_1.setIcon(new ThemeResource("images/icons/updates/horizLine.png"));
		label_2.setIcon(new ThemeResource("images/icons/updates/horizLine.png"));
		label_3.setIcon(new ThemeResource("images/icons/updates/horizLine.png"));
		
		//label_4.setIcon(new ThemeResource("images/icons/updates/vertLine.png"));
		//label_5.setIcon(new ThemeResource("images/icons/updates/vertLine.png"));
		//label_6.setIcon(new ThemeResource("images/icons/updates/vertLine.png"));
		//label_7.setIcon(new ThemeResource("images/icons/updates/vertLine.png"));
		
		//root cards formatting
		//root_button1.setStyleName("root1");
		//root_button2.setStyleName("root2");
		
		//verticalLayout_3.setStyleName("center");
		//verticalLayout_root.setStyleName("white");
		//panel_1.setStyleName("borderless");
		
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("1000px");
		mainLayout.setMargin(false);
		mainLayout.setRows(3);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("1000px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, 0, 0);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2, 0, 1);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3, 0, 2);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("400px");
		horizontalLayout_1.setMargin(false);
		
		// trendingCards_1
		trendingCards_1 = new TrendingCards();
		trendingCards_1.setImmediate(false);
		trendingCards_1.setWidth("100.0%");
		trendingCards_1.setHeight("350px");
		horizontalLayout_1.addComponent(trendingCards_1);
		horizontalLayout_1.setComponentAlignment(trendingCards_1,
				new Alignment(48));
		
		// trendingTags_2
		trendingTags_2 = new TrendingTags();
		trendingTags_2.setImmediate(false);
		trendingTags_2.setWidth("100.0%");
		trendingTags_2.setHeight("350px");
		horizontalLayout_1.addComponent(trendingTags_2);
		horizontalLayout_1.setComponentAlignment(trendingTags_2, new Alignment(
				48));
		
		// recentlyPlayed_1
		recentlyPlayed_1 = new RecentlyPlayed();
		recentlyPlayed_1.setImmediate(false);
		recentlyPlayed_1.setWidth("100.0%");
		recentlyPlayed_1.setHeight("350px");
		horizontalLayout_1.addComponent(recentlyPlayed_1);
		horizontalLayout_1.setComponentAlignment(recentlyPlayed_1,
				new Alignment(48));
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("100.0%");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("2px");
		label_1.setValue("Label");
		horizontalLayout_2.addComponent(label_1);
		horizontalLayout_2.setComponentAlignment(label_1, new Alignment(48));
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Label");
		horizontalLayout_2.addComponent(label_2);
		horizontalLayout_2.setComponentAlignment(label_2, new Alignment(48));
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Label");
		horizontalLayout_2.addComponent(label_3);
		horizontalLayout_2.setComponentAlignment(label_3, new Alignment(48));
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("100.0%");
		horizontalLayout_3.setHeight("400px");
		horizontalLayout_3.setMargin(false);
		
		// popularCards_1
		popularCards_1 = new PopularCards();
		popularCards_1.setImmediate(false);
		popularCards_1.setWidth("100.0%");
		popularCards_1.setHeight("350px");
		horizontalLayout_3.addComponent(popularCards_1);
		horizontalLayout_3.setComponentAlignment(popularCards_1, new Alignment(
				48));
		
		// popularTags_2
		popularTags_2 = new PopularTags();
		popularTags_2.setImmediate(false);
		popularTags_2.setWidth("100.0%");
		popularTags_2.setHeight("350px");
		horizontalLayout_3.addComponent(popularTags_2);
		horizontalLayout_3.setComponentAlignment(popularTags_2, new Alignment(
				48));
		
		// popularCards_2
		popularCards_2 = new PopularCards();
		popularCards_2.setImmediate(false);
		popularCards_2.setWidth("100.0%");
		popularCards_2.setHeight("350px");
		horizontalLayout_3.addComponent(popularCards_2);
		horizontalLayout_3.setComponentAlignment(popularCards_2, new Alignment(
				48));
		
		return horizontalLayout_3;
	}

}
