/**
 * @Author: Eric H Correia
 *
 * This class creates a container to hold the top 15 most popular tags played so far during the game
 * 
 */

package com.example.mmowgli_updates;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class PopularTags extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private GridLayout link_container;
	@AutoGenerated
	private Label label_title;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	public PopularTags() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}
	
	public GridLayout getLink_container() {
		return link_container;
	}

	public void setLink_container(GridLayout link_container) {
		this.link_container = link_container;
	}

	public Label getLabel_title() {
		return label_title;
	}

	public void setLabel_title(Label label_title) {
		this.label_title = label_title;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_title
		label_title = new Label();
		label_title.setStyleName("title");
		label_title.setImmediate(false);
		label_title.setWidth("-1px");
		label_title.setHeight("-1px");
		label_title.setValue("All Time Most popular Tags");
		mainLayout.addComponent(label_title);
		mainLayout.setExpandRatio(label_title, 0.155f);
		mainLayout.setComponentAlignment(label_title, new Alignment(24));
		
		// link_container
		link_container = new GridLayout();
		link_container.setImmediate(false);
		link_container.setWidth("85.0%");
		link_container.setHeight("100.0%");
		link_container.setMargin(false);
		link_container.setColumns(3);
		link_container.setRows(5);
		mainLayout.addComponent(link_container);
		mainLayout.setExpandRatio(link_container, 1.0f);
		mainLayout.setComponentAlignment(link_container, new Alignment(48));
		
		return mainLayout;
	}

}
