/**
 * @Author: Eric H Correia
 *
 * This class creates 
 * 
 */

package com.example.mmowgli_updates;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;

public class PopularCards extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private Label label_popular;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PopularCards() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		//initPopularCardsList();
		
	}

	public GridLayout getMainLayout() {
		return mainLayout;
	}

	public void setMainLayout(GridLayout mainLayout) {
		this.mainLayout = mainLayout;
	}

	public Label getLabel_popular() {
		return label_popular;
	}

	public void setLabel_popular(Label label_popular) {
		this.label_popular = label_popular;
	}
	
	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		mainLayout.setRows(6);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_popular
		label_popular = new Label();
		label_popular.setImmediate(false);
		label_popular.setWidth("-1px");
		label_popular.setHeight("-1px");
		label_popular.setValue("All Time Most Popular Cards");
		mainLayout.addComponent(label_popular, 0, 0);
		mainLayout.setComponentAlignment(label_popular, new Alignment(48));
		
		return mainLayout;
	}


}
