package com.example.mmowgli_updates;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.VerticalLayout;

public class RecentlyPlayed extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_5;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private NativeButton nativeButton_explore;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private NativeButton nativeButton_adapt;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private NativeButton nativeButton_expand;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private NativeButton nativeButton_counter;
	@AutoGenerated
	private Label label_played;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RecentlyPlayed() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		nativeButton_counter.setStyleName("counter");
		nativeButton_expand.setStyleName("expand");
		nativeButton_adapt.setStyleName("adapt");
		nativeButton_explore.setStyleName("explore");
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_played
		label_played = new Label();
		label_played.setImmediate(false);
		label_played.setWidth("-1px");
		label_played.setHeight("-1px");
		label_played.setValue("Most Recently Played");
		mainLayout.addComponent(label_played);
		mainLayout.setComponentAlignment(label_played, new Alignment(24));
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		mainLayout.addComponent(verticalLayout_2);
		mainLayout.setComponentAlignment(verticalLayout_2, new Alignment(20));
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		mainLayout.addComponent(verticalLayout_3);
		mainLayout.setComponentAlignment(verticalLayout_3, new Alignment(20));
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		mainLayout.addComponent(verticalLayout_4);
		mainLayout.setComponentAlignment(verticalLayout_4, new Alignment(20));
		
		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		mainLayout.addComponent(verticalLayout_5);
		mainLayout.setComponentAlignment(verticalLayout_5, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("70.0%");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		
		// nativeButton_counter
		nativeButton_counter = new NativeButton();
		nativeButton_counter.setCaption("1. Counter - Look into the issue...");
		nativeButton_counter.setImmediate(true);
		nativeButton_counter.setWidth("100.0%");
		nativeButton_counter.setHeight("-1px");
		verticalLayout_2.addComponent(nativeButton_counter);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("by: user2000 - 05/01/15");
		verticalLayout_2.addComponent(label_1);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("70.0%");
		verticalLayout_3.setHeight("-1px");
		verticalLayout_3.setMargin(false);
		
		// nativeButton_expand
		nativeButton_expand = new NativeButton();
		nativeButton_expand.setCaption("2. Expand - Look into the issue...");
		nativeButton_expand.setImmediate(true);
		nativeButton_expand.setWidth("100.0%");
		nativeButton_expand.setHeight("-1px");
		verticalLayout_3.addComponent(nativeButton_expand);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("by: user2001 - 05/01/15");
		verticalLayout_3.addComponent(label_2);
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("70.0%");
		verticalLayout_4.setHeight("-1px");
		verticalLayout_4.setMargin(false);
		
		// nativeButton_adapt
		nativeButton_adapt = new NativeButton();
		nativeButton_adapt.setCaption("3. Adapt - Look into the issue...");
		nativeButton_adapt.setImmediate(true);
		nativeButton_adapt.setWidth("100.0%");
		nativeButton_adapt.setHeight("-1px");
		verticalLayout_4.addComponent(nativeButton_adapt);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("by: user2002 - 05/01/15");
		verticalLayout_4.addComponent(label_3);
		
		return verticalLayout_4;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("70.0%");
		verticalLayout_5.setHeight("-1px");
		verticalLayout_5.setMargin(false);
		
		// nativeButton_explore
		nativeButton_explore = new NativeButton();
		nativeButton_explore.setCaption("4. Explore - Look into the issue...");
		nativeButton_explore.setImmediate(true);
		nativeButton_explore.setWidth("100.0%");
		nativeButton_explore.setHeight("-1px");
		verticalLayout_5.addComponent(nativeButton_explore);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("by: user2003 - 05/01/15");
		verticalLayout_5.addComponent(label_4);
		
		return verticalLayout_5;
	}

}
