package com.example.mmowgli_2_0;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.VerticalLayout;

public class CardView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private NativeButton nativeButton_4;
	@AutoGenerated
	private NativeButton nativeButton_3;
	@AutoGenerated
	private NativeButton nativeButton_2;
	@AutoGenerated
	private NativeButton nativeButton_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private NativeButton nativeButton_5;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private NativeButton button_favorite;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private NativeButton button_downvote;
	@AutoGenerated
	private NativeButton button_upvote;
	@AutoGenerated
	private Label label_voteCount;
	@AutoGenerated
	private Label label_date;
	@AutoGenerated
	private Link link_user;
	@AutoGenerated
	private Label label_cardType;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CardView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("340px");
		mainLayout.setHeight("200px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("340px");
		setHeight("200px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		mainLayout.setExpandRatio(horizontalLayout_1, 1.0f);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		mainLayout.setExpandRatio(horizontalLayout_2, 1.0f);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3);
		mainLayout.setExpandRatio(horizontalLayout_3, 0.1f);
		mainLayout.setComponentAlignment(horizontalLayout_3, new Alignment(24));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("100.0%");
		horizontalLayout_1.setMargin(false);
		
		// label_cardType
		label_cardType = new Label();
		label_cardType.setImmediate(false);
		label_cardType.setWidth("-1px");
		label_cardType.setHeight("-1px");
		label_cardType.setValue("Label");
		horizontalLayout_1.addComponent(label_cardType);
		
		// link_user
		link_user = new Link();
		link_user.setCaption("Link");
		link_user.setImmediate(false);
		link_user.setWidth("-1px");
		link_user.setHeight("-1px");
		horizontalLayout_1.addComponent(link_user);
		
		// label_date
		label_date = new Label();
		label_date.setImmediate(false);
		label_date.setWidth("-1px");
		label_date.setHeight("-1px");
		label_date.setValue("Label");
		horizontalLayout_1.addComponent(label_date);
		
		// label_voteCount
		label_voteCount = new Label();
		label_voteCount.setImmediate(false);
		label_voteCount.setWidth("-1px");
		label_voteCount.setHeight("-1px");
		label_voteCount.setValue("Label");
		horizontalLayout_1.addComponent(label_voteCount);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_1.addComponent(verticalLayout_2);
		
		// button_favorite
		button_favorite = new NativeButton();
		button_favorite.setCaption("NativeButton");
		button_favorite.setImmediate(false);
		button_favorite.setWidth("-1px");
		button_favorite.setHeight("-1px");
		horizontalLayout_1.addComponent(button_favorite);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		
		// button_upvote
		button_upvote = new NativeButton();
		button_upvote.setCaption("NativeButton");
		button_upvote.setImmediate(false);
		button_upvote.setWidth("-1px");
		button_upvote.setHeight("-1px");
		verticalLayout_2.addComponent(button_upvote);
		
		// button_downvote
		button_downvote = new NativeButton();
		button_downvote.setCaption("NativeButton");
		button_downvote.setImmediate(false);
		button_downvote.setWidth("-1px");
		button_downvote.setHeight("-1px");
		verticalLayout_2.addComponent(button_downvote);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("100.0%");
		horizontalLayout_2.setHeight("100.0%");
		horizontalLayout_2.setMargin(false);
		
		// nativeButton_5
		nativeButton_5 = new NativeButton();
		nativeButton_5.setCaption("NativeButton");
		nativeButton_5.setImmediate(false);
		nativeButton_5.setWidth("100.0%");
		nativeButton_5.setHeight("100.0%");
		horizontalLayout_2.addComponent(nativeButton_5);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		
		// nativeButton_1
		nativeButton_1 = new NativeButton();
		nativeButton_1.setCaption("NativeButton");
		nativeButton_1.setImmediate(false);
		nativeButton_1.setWidth("-1px");
		nativeButton_1.setHeight("-1px");
		horizontalLayout_3.addComponent(nativeButton_1);
		
		// nativeButton_2
		nativeButton_2 = new NativeButton();
		nativeButton_2.setCaption("NativeButton");
		nativeButton_2.setImmediate(false);
		nativeButton_2.setWidth("-1px");
		nativeButton_2.setHeight("-1px");
		horizontalLayout_3.addComponent(nativeButton_2);
		
		// nativeButton_3
		nativeButton_3 = new NativeButton();
		nativeButton_3.setCaption("NativeButton");
		nativeButton_3.setImmediate(false);
		nativeButton_3.setWidth("-1px");
		nativeButton_3.setHeight("-1px");
		horizontalLayout_3.addComponent(nativeButton_3);
		
		// nativeButton_4
		nativeButton_4 = new NativeButton();
		nativeButton_4.setCaption("NativeButton");
		nativeButton_4.setImmediate(false);
		nativeButton_4.setWidth("-1px");
		nativeButton_4.setHeight("-1px");
		horizontalLayout_3.addComponent(nativeButton_4);
		
		return horizontalLayout_3;
	}

}
