package com.example.mmowgli_2_0;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.VerticalLayout;

public class CardView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private NativeButton nativeButton_4;
	@AutoGenerated
	private NativeButton nativeButton_3;
	@AutoGenerated
	private NativeButton nativeButton_2;
	@AutoGenerated
	private NativeButton nativeButton_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private NativeButton nativeButton_5;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private NativeButton nativeButton_8;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private NativeButton nativeButton_7;
	@AutoGenerated
	private NativeButton nativeButton_6;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Link link_1;
	@AutoGenerated
	private Label label_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CardView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("340px");
		mainLayout.setHeight("200px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("340px");
		setHeight("200px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		mainLayout.setExpandRatio(horizontalLayout_1, 1.0f);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		mainLayout.setExpandRatio(horizontalLayout_2, 1.0f);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3);
		mainLayout.setExpandRatio(horizontalLayout_3, 0.1f);
		mainLayout.setComponentAlignment(horizontalLayout_3, new Alignment(24));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("100.0%");
		horizontalLayout_1.setMargin(false);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Label");
		horizontalLayout_1.addComponent(label_1);
		
		// link_1
		link_1 = new Link();
		link_1.setCaption("Link");
		link_1.setImmediate(false);
		link_1.setWidth("-1px");
		link_1.setHeight("-1px");
		horizontalLayout_1.addComponent(link_1);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Label");
		horizontalLayout_1.addComponent(label_2);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Label");
		horizontalLayout_1.addComponent(label_3);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_1.addComponent(verticalLayout_2);
		
		// nativeButton_8
		nativeButton_8 = new NativeButton();
		nativeButton_8.setCaption("NativeButton");
		nativeButton_8.setImmediate(false);
		nativeButton_8.setWidth("-1px");
		nativeButton_8.setHeight("-1px");
		horizontalLayout_1.addComponent(nativeButton_8);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		
		// nativeButton_6
		nativeButton_6 = new NativeButton();
		nativeButton_6.setCaption("NativeButton");
		nativeButton_6.setImmediate(false);
		nativeButton_6.setWidth("-1px");
		nativeButton_6.setHeight("-1px");
		verticalLayout_2.addComponent(nativeButton_6);
		
		// nativeButton_7
		nativeButton_7 = new NativeButton();
		nativeButton_7.setCaption("NativeButton");
		nativeButton_7.setImmediate(false);
		nativeButton_7.setWidth("-1px");
		nativeButton_7.setHeight("-1px");
		verticalLayout_2.addComponent(nativeButton_7);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("100.0%");
		horizontalLayout_2.setHeight("100.0%");
		horizontalLayout_2.setMargin(false);
		
		// nativeButton_5
		nativeButton_5 = new NativeButton();
		nativeButton_5.setCaption("NativeButton");
		nativeButton_5.setImmediate(false);
		nativeButton_5.setWidth("100.0%");
		nativeButton_5.setHeight("100.0%");
		horizontalLayout_2.addComponent(nativeButton_5);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		
		// nativeButton_1
		nativeButton_1 = new NativeButton();
		nativeButton_1.setCaption("NativeButton");
		nativeButton_1.setImmediate(false);
		nativeButton_1.setWidth("-1px");
		nativeButton_1.setHeight("-1px");
		horizontalLayout_3.addComponent(nativeButton_1);
		
		// nativeButton_2
		nativeButton_2 = new NativeButton();
		nativeButton_2.setCaption("NativeButton");
		nativeButton_2.setImmediate(false);
		nativeButton_2.setWidth("-1px");
		nativeButton_2.setHeight("-1px");
		horizontalLayout_3.addComponent(nativeButton_2);
		
		// nativeButton_3
		nativeButton_3 = new NativeButton();
		nativeButton_3.setCaption("NativeButton");
		nativeButton_3.setImmediate(false);
		nativeButton_3.setWidth("-1px");
		nativeButton_3.setHeight("-1px");
		horizontalLayout_3.addComponent(nativeButton_3);
		
		// nativeButton_4
		nativeButton_4 = new NativeButton();
		nativeButton_4.setCaption("NativeButton");
		nativeButton_4.setImmediate(false);
		nativeButton_4.setWidth("-1px");
		nativeButton_4.setHeight("-1px");
		horizontalLayout_3.addComponent(nativeButton_4);
		
		return horizontalLayout_3;
	}

}
