package com.example.mmowgli_2_0;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.TextFileProperty;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;

public class DocEditor extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private TextArea html;
	@AutoGenerated
	private RichTextArea WYSIWYG;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DocEditor() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1, "top:60.0px;left:80.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("540px");
		tabSheet_1.setHeight("620px");
		
		// WYSIWYG
		WYSIWYG = new RichTextArea();
		WYSIWYG.setImmediate(false);
		WYSIWYG.setWidth("100.0%");
		WYSIWYG.setHeight("100.0%");
		tabSheet_1.addTab(WYSIWYG, "WYSIWYG", null);
		
		// html
		html = new TextArea();
		html.setImmediate(false);
		html.setWidth("100.0%");
		html.setHeight("100.0%");
		tabSheet_1.addTab(html, "HTML", null);
		
		return tabSheet_1;
	}

	//implement Data source to be used when handling events
	public void setPropertyDataSource(TextFileProperty doc) {
		// TODO Auto-generated method stub
		html.setPropertyDataSource(doc);
		WYSIWYG.setPropertyDataSource(doc);
		
	}
}
