package com.example.mmowgli_2_0;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;

public class HomePageUpdates extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private GridLayout mainLayout;

	@AutoGenerated
	private PopularTags popularTags_2;

	@AutoGenerated
	private TrendingTags trendingTags_2;

	private PopularTags popularTagList;
	private TrendingTags trendingTagList;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HomePageUpdates() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
//		mainLayout.setWidth("auto");
//		mainLayout.setHeight("auto");
//		
//		trendingTagList = new TrendingTags();
//		mainLayout.addComponent(trendingTagList, 1, 0);
//		mainLayout.setComponentAlignment(trendingTagList,
//				new Alignment(48));
//		
//		
//		popularTagList = new PopularTags();
//		mainLayout.addComponent(popularTagList, 1, 1);
//		mainLayout.setComponentAlignment(popularTagList,
//				new Alignment(48));
		
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setColumns(3);
		mainLayout.setRows(2);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// trendingTags_2
		trendingTags_2 = new TrendingTags();
		trendingTags_2.setImmediate(false);
		trendingTags_2.setWidth("-1px");
		trendingTags_2.setHeight("-1px");
		mainLayout.addComponent(trendingTags_2, 1, 0);
		mainLayout.setComponentAlignment(trendingTags_2, new Alignment(48));
		
		// popularTags_2
		popularTags_2 = new PopularTags();
		popularTags_2.setImmediate(false);
		popularTags_2.setWidth("-1px");
		popularTags_2.setHeight("-1px");
		mainLayout.addComponent(popularTags_2, 1, 1);
		mainLayout.setComponentAlignment(popularTags_2, new Alignment(48));
		
		return mainLayout;
	}

}
