package com.example.mmowgli_2_0;

import com.example.mmowgli_explore.CardExplorationView;
import com.example.mmowgli_updates.HomePageUpdates;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class HomePage extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Panel panel_2;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Footer footer_1;
	@AutoGenerated
	private CardExplorationView cardExplorationView_1;
	@AutoGenerated
	private HomePageUpdates homePageUpdates_1;
	@AutoGenerated
	private VideoDisplayer videoDisplayer_1;
	@AutoGenerated
	private SideBar sideBar_1;
	@AutoGenerated
	private TopBar topBar_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HomePage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		topBar_1.setStyleName("topbar");
		sideBar_1.setStyleName("sidebar");
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// topBar_1
		topBar_1 = new TopBar();
		topBar_1.setImmediate(false);
		topBar_1.setWidth("100.0%");
		topBar_1.setHeight("100.0%");
		mainLayout.addComponent(topBar_1);
		mainLayout.setExpandRatio(topBar_1, 0.07f);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		mainLayout.setExpandRatio(horizontalLayout_2, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("100.0%");
		horizontalLayout_2.setHeight("100.0%");
		horizontalLayout_2.setMargin(false);
		
		// sideBar_1
		sideBar_1 = new SideBar();
		sideBar_1.setImmediate(false);
		sideBar_1.setWidth("160px");
		sideBar_1.setHeight("100.0%");
		horizontalLayout_2.addComponent(sideBar_1);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_2.addComponent(verticalLayout_2);
		horizontalLayout_2.setExpandRatio(verticalLayout_2, 1.0f);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		
		// videoDisplayer_1
		videoDisplayer_1 = new VideoDisplayer();
		videoDisplayer_1.setImmediate(false);
		videoDisplayer_1.setWidth("100.0%");
		videoDisplayer_1.setHeight("-1px");
		verticalLayout_2.addComponent(videoDisplayer_1);
		
		// panel_2
		panel_2 = buildPanel_2();
		verticalLayout_2.addComponent(panel_2);
		verticalLayout_2.setExpandRatio(panel_2, 1.0f);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setImmediate(false);
		panel_2.setWidth("100.0%");
		panel_2.setHeight("100.0%");
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		panel_2.setContent(gridLayout_1);
		
		return panel_2;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("1120px");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setRows(3);
		
		// homePageUpdates_1
		homePageUpdates_1 = new HomePageUpdates();
		homePageUpdates_1.setImmediate(false);
		homePageUpdates_1.setWidth("100.0%");
		homePageUpdates_1.setHeight("-1px");
		gridLayout_1.addComponent(homePageUpdates_1, 0, 0);
		gridLayout_1
				.setComponentAlignment(homePageUpdates_1, new Alignment(33));
		
		// cardExplorationView_1
		cardExplorationView_1 = new CardExplorationView();
		cardExplorationView_1.setImmediate(false);
		cardExplorationView_1.setWidth("100.0%");
		cardExplorationView_1.setHeight("-1px");
		gridLayout_1.addComponent(cardExplorationView_1, 0, 1);
		
		// footer_1
		footer_1 = new Footer();
		footer_1.setImmediate(false);
		footer_1.setWidth("100.0%");
		footer_1.setHeight("-1px");
		gridLayout_1.addComponent(footer_1, 0, 2);
		gridLayout_1.setComponentAlignment(footer_1, new Alignment(9));
		
		return gridLayout_1;
	}

}
