package com.example.mmowgli_2_0;

import com.example.mmowgli_updates.PopularTags;
import com.example.mmowgli_updates.TrendingTags;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ExternalResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.VerticalLayout;

public class RootCards extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private VerticalLayout verticalLayout_root;

	@AutoGenerated
	private HorizontalLayout test_layout;

	@AutoGenerated
	private NativeButton root_button2;

	@AutoGenerated
	private NativeButton root_button1;

	@AutoGenerated
	private NativeButton toggle_video;

	private PopularTags popularTagList;
	private TrendingTags trendingTagList;
	
	private boolean showRootCards = true;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RootCards() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		
		Embedded myVid = new Embedded("BlackSwan", new ExternalResource("https://youtu.be/fAfRuU78X34"));
		
		//Set the toggle Settings
		initToggle();
		
		//root cards formatting
		root_button1.setStyleName("root1");
		root_button2.setStyleName("root2");
		
		//verticalLayout_3.setStyleName("center");
		verticalLayout_root.setStyleName("white");
		//panel_1.setStyleName("borderless");
		
	}
	
	private void initToggle(){
		
		//toogle root cards
		toggle_video.setCaption(null);
		toggle_video.setIcon(new ThemeResource("images/icons/updates/threeDots.png"));
		toggle_video.setStyleName("videoDisplay");

				
		toggle_video.addClickListener(new NativeButton.ClickListener() {
					
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				showRootCards = !showRootCards;
				test_layout.setVisible(showRootCards);
						
				//if true the rootcards are now invisible -> remove the extra space on screen
				//else the root cards are now visible -> add space on screen
				if(showRootCards == false)
				{
					//rootButton_Ratio = 40.0f;
					mainLayout.setExpandRatio(verticalLayout_root, 0.05f);
							
					//handle the spacing of the different updates 
					//verticalLayout_3.setExpandRatio(horizontalLayout_1, 2.25f);
				}
				else 
				{
					//rootButton_Ratio = 5.0f;
					mainLayout.setExpandRatio(verticalLayout_root, 0.33f);
							
					//handle the spacing of the different updates 
					//verticalLayout_3.setExpandRatio(horizontalLayout_1, 3.0f);

				}
						
			}
		});
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_root
		verticalLayout_root = buildVerticalLayout_root();
		mainLayout.addComponent(verticalLayout_root);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_root() {
		// common part: create layout
		verticalLayout_root = new VerticalLayout();
		verticalLayout_root.setImmediate(false);
		verticalLayout_root.setWidth("100.0%");
		verticalLayout_root.setHeight("-1px");
		verticalLayout_root.setMargin(false);
		
		// toggle_video
		toggle_video = new NativeButton();
		toggle_video.setCaption("NativeButton");
		toggle_video.setImmediate(true);
		toggle_video.setWidth("100.0%");
		toggle_video.setHeight("-1px");
		verticalLayout_root.addComponent(toggle_video);
		verticalLayout_root.setComponentAlignment(toggle_video, new Alignment(
				20));
		
		// test_layout
		test_layout = buildTest_layout();
		verticalLayout_root.addComponent(test_layout);
		verticalLayout_root.setExpandRatio(test_layout, 0.1f);
		verticalLayout_root.setComponentAlignment(test_layout,
				new Alignment(20));
		
		return verticalLayout_root;
	}

	@AutoGenerated
	private HorizontalLayout buildTest_layout() {
		// common part: create layout
		test_layout = new HorizontalLayout();
		test_layout.setImmediate(false);
		test_layout.setWidth("100.0%");
		test_layout.setHeight("100.0%");
		test_layout.setMargin(false);
		
		// root_button1
		root_button1 = new NativeButton();
		root_button1.setCaption("root1");
		root_button1.setImmediate(true);
		root_button1.setWidth("399px");
		root_button1.setHeight("134px");
		test_layout.addComponent(root_button1);
		test_layout.setExpandRatio(root_button1, 0.5f);
		test_layout.setComponentAlignment(root_button1, new Alignment(48));
		
		// root_button2
		root_button2 = new NativeButton();
		root_button2.setCaption("root2");
		root_button2.setImmediate(true);
		root_button2.setWidth("399px");
		root_button2.setHeight("134px");
		test_layout.addComponent(root_button2);
		test_layout.setExpandRatio(root_button2, 0.5f);
		test_layout.setComponentAlignment(root_button2, new Alignment(48));
		
		return test_layout;
	}

}
