package com.example.mmowgli_2_0;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;

public class SideBar extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private Button button_leaderboard;
	@AutoGenerated
	private Button button_help;
	@AutoGenerated
	private Button button_blog;
	@AutoGenerated
	private Button button_map;
	@AutoGenerated
	private Button button_path;
	@AutoGenerated
	private Button button_action;
	@AutoGenerated
	private Button button_idea;
	@AutoGenerated
	private Button button_search;
	@AutoGenerated
	private Button button_notifications;
	@AutoGenerated
	private Button button_profile;
	@AutoGenerated
	private Button button_home;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SideBar() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setRows(12);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// button_home
		button_home = new Button();
		button_home.setCaption("Home");
		button_home.setImmediate(true);
		button_home.setWidth("100.0%");
		button_home.setHeight("100.0%");
		mainLayout.addComponent(button_home, 0, 0);
		mainLayout.setComponentAlignment(button_home, new Alignment(48));
		
		// button_profile
		button_profile = new Button();
		button_profile.setCaption("Profile");
		button_profile.setImmediate(true);
		button_profile.setWidth("100.0%");
		button_profile.setHeight("100.0%");
		mainLayout.addComponent(button_profile, 0, 1);
		
		// button_notifications
		button_notifications = new Button();
		button_notifications.setCaption("Notifications");
		button_notifications.setImmediate(true);
		button_notifications.setWidth("100.0%");
		button_notifications.setHeight("100.0%");
		mainLayout.addComponent(button_notifications, 0, 2);
		
		// button_search
		button_search = new Button();
		button_search.setCaption("Search");
		button_search.setImmediate(true);
		button_search.setWidth("100.0%");
		button_search.setHeight("100.0%");
		mainLayout.addComponent(button_search, 0, 3);
		
		// button_idea
		button_idea = new Button();
		button_idea.setCaption("Play Idea");
		button_idea.setImmediate(true);
		button_idea.setWidth("100.0%");
		button_idea.setHeight("100.0%");
		mainLayout.addComponent(button_idea, 0, 4);
		
		// button_action
		button_action = new Button();
		button_action.setCaption("Take Action");
		button_action.setImmediate(true);
		button_action.setWidth("100.0%");
		button_action.setHeight("100.0%");
		mainLayout.addComponent(button_action, 0, 5);
		
		// button_path
		button_path = new Button();
		button_path.setCaption("Recommended Path");
		button_path.setImmediate(true);
		button_path.setWidth("100.0%");
		button_path.setHeight("100.0%");
		mainLayout.addComponent(button_path, 0, 6);
		
		// button_map
		button_map = new Button();
		button_map.setCaption("Map");
		button_map.setImmediate(true);
		button_map.setWidth("100.0%");
		button_map.setHeight("100.0%");
		mainLayout.addComponent(button_map, 0, 7);
		
		// button_blog
		button_blog = new Button();
		button_blog.setCaption("Blog");
		button_blog.setImmediate(true);
		button_blog.setWidth("100.0%");
		button_blog.setHeight("100.0%");
		mainLayout.addComponent(button_blog, 0, 8);
		
		// button_help
		button_help = new Button();
		button_help.setCaption("Learn More / Help");
		button_help.setImmediate(true);
		button_help.setWidth("100.0%");
		button_help.setHeight("100.0%");
		mainLayout.addComponent(button_help, 0, 9);
		
		// button_leaderboard
		button_leaderboard = new Button();
		button_leaderboard.setCaption("Leaderboard");
		button_leaderboard.setImmediate(true);
		button_leaderboard.setWidth("100.0%");
		button_leaderboard.setHeight("100.0%");
		mainLayout.addComponent(button_leaderboard, 0, 10);
		
		return mainLayout;
	}

}
