/**
 * @Author: Eric H Correia
 *
 * This class creates 
 * 
 */

package com.example.mmowgli_2_0;

import com.example.mmowgli_updates.PopularTags;
import com.example.mmowgli_updates.TrendingTags;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ExternalResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Flash;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.VerticalLayout;

public class VideoDisplayer extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private VerticalLayout verticalLayout_root;

	@AutoGenerated
	private NativeButton toggle_video;

	@AutoGenerated
	private HorizontalLayout test_layout;

	@AutoGenerated
	private GridLayout gridLayout_1;

	@AutoGenerated
	private Label videoDescription;

	@AutoGenerated
	private Label videoTitle;

	private PopularTags popularTagList;
	private TrendingTags trendingTagList;
	
	private boolean showRootCards = true;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VideoDisplayer() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		
		Flash myVid = new Flash(null, new ExternalResource("http://www.youtube.com/v/watch?v=fAfRuU78X34"));
		//myVid.setAlternateText("Vaadin Eclipse Quickstart video");
		//myVid.setType(Embedded.TYPE_OBJECT);
		//myVid.setMimeType("application/x-shockwave-flash");
		myVid.setParameter("allowFullScreen", "true");
		myVid.setWidth(350.0f, Unit.PIXELS);
		myVid.setHeight(255.0f, Unit.PIXELS);
	    test_layout.addComponent(myVid, 0);
		
		//embedded_BlackSwan.setType(Embedded.TYPE_OBJECT);
		
		//Set the toggle Settings
		initToggle();
		
		//Video text
		videoTitle.setValue("WELCOME TO THE BLACKSWAN MMOWGLI GAME");
		videoDescription.setValue("Call me Ishmael. Some years ago--never mind how long precisely--having little or no money in my purse, "
				+ "and nothing particular to interest me on shore, I thought I would sail about a little and see the watery "
				+ "part of the world. It is a way I have of driving off the spleen and regulating the circulation. "
				+ "Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; "
				+ "whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; "
				+ "and especially whenever my hypos get such an upper hand of me, "
				+ "that it requires a strong moral principle to prevent me from deliberately stepping into the street, "
				+ "and methodically knocking people's hats off--then, I account it high time to get to sea as soon as I can.");
		
		videoDescription.setStyleName("videoDescription");
		
		//verticalLayout_3.setStyleName("center");
		verticalLayout_root.setStyleName("white");
		//panel_1.setStyleName("borderless");
		
	}
	
	private void initToggle(){
		
		//toogle root cards
		toggle_video.setCaption(null);
		toggle_video.setIcon(new ThemeResource("images/icons/updates/threeDots.png"));
		toggle_video.setStyleName("videoDisplay");

				
		toggle_video.addClickListener(new NativeButton.ClickListener() {
					
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				showRootCards = !showRootCards;
				test_layout.setVisible(showRootCards);
						
				//if true the rootcards are now invisible -> remove the extra space on screen
				//else the root cards are now visible -> add space on screen
				if(showRootCards == false)
				{
					//rootButton_Ratio = 40.0f;
					mainLayout.setExpandRatio(verticalLayout_root, 0.05f);
							
					//handle the spacing of the different updates 
					//verticalLayout_3.setExpandRatio(horizontalLayout_1, 2.25f);
				}
				else 
				{
					//rootButton_Ratio = 5.0f;
					mainLayout.setExpandRatio(verticalLayout_root, 0.33f);
							
					//handle the spacing of the different updates 
					//verticalLayout_3.setExpandRatio(horizontalLayout_1, 3.0f);

				}
						
			}
		});
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_root
		verticalLayout_root = buildVerticalLayout_root();
		mainLayout.addComponent(verticalLayout_root);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_root() {
		// common part: create layout
		verticalLayout_root = new VerticalLayout();
		verticalLayout_root.setImmediate(false);
		verticalLayout_root.setWidth("100.0%");
		verticalLayout_root.setHeight("-1px");
		verticalLayout_root.setMargin(false);
		
		// test_layout
		test_layout = buildTest_layout();
		verticalLayout_root.addComponent(test_layout);
		verticalLayout_root.setComponentAlignment(test_layout,
				new Alignment(20));
		
		// toggle_video
		toggle_video = new NativeButton();
		toggle_video.setCaption("NativeButton");
		toggle_video.setImmediate(true);
		toggle_video.setWidth("100.0%");
		toggle_video.setHeight("-1px");
		verticalLayout_root.addComponent(toggle_video);
		verticalLayout_root.setExpandRatio(toggle_video, 1.0f);
		
		return verticalLayout_root;
	}

	@AutoGenerated
	private HorizontalLayout buildTest_layout() {
		// common part: create layout
		test_layout = new HorizontalLayout();
		test_layout.setImmediate(false);
		test_layout.setWidth("100.0%");
		test_layout.setHeight("-1px");
		test_layout.setMargin(true);
		test_layout.setSpacing(true);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		test_layout.addComponent(gridLayout_1);
		test_layout.setExpandRatio(gridLayout_1, 1.0f);
		
		return test_layout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setRows(2);
		
		// videoTitle
		videoTitle = new Label();
		videoTitle.setImmediate(false);
		videoTitle.setWidth("-1px");
		videoTitle.setHeight("-1px");
		videoTitle.setValue("Label");
		gridLayout_1.addComponent(videoTitle, 0, 0);
		
		// videoDescription
		videoDescription = new Label();
		videoDescription.setImmediate(false);
		videoDescription.setWidth("-1px");
		videoDescription.setHeight("-1px");
		videoDescription.setValue("Label");
		gridLayout_1.addComponent(videoDescription, 0, 1);
		
		return gridLayout_1;
	}

}
